# Generated by Django 4.0.2 on 2022-02-14 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('page', '0001_initial'),
        ('module', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='module',
            name='pages',
            field=models.ManyToManyField(to='page.Page'),
        ),
    ]
