# Generated by Django 4.0.2 on 2022-02-13 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('module', '0001_initial'),
        ('classroom', '0003_course_enrolled'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='module',
            field=models.ManyToManyField(to='module.Module'),
        ),
    ]
