# Generated by Django 4.0.2 on 2022-02-13 17:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('classroom', '0004_course_module'),
    ]

    operations = [
        migrations.RenameField(
            model_name='course',
            old_name='module',
            new_name='modules',
        ),
    ]
